# Generated by Django 4.2.18 on 2025-05-31 13:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filled_at', models.DateField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=16, max_digits=40, validators=[django.core.validators.MinValueValidator(1e-12)])),
                ('amount', models.DecimalField(decimal_places=8, max_digits=32, validators=[django.core.validators.MinValueValidator(1e-12)])),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='maker_trades', to='order.order')),
                ('taker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='taker_trades', to='order.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
