# Generated by Django 4.2.18 on 2025-05-31 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, unique=True)),
                ('symbol', models.CharField(max_length=8, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filled_at', models.DateField(blank=True, null=True)),
                ('symbol', models.CharField(db_index=True, max_length=17, null=True, unique=True)),
                ('state', models.CharField(choices=[('Active', 'active'), ('Suspend', 'suspend'), ('Deactive', 'deactive')], default='Active', max_length=15)),
                ('first_currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='market_first_currency', to='market.currency')),
                ('second_currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='market_second_currency', to='market.currency')),
            ],
            options={
                'unique_together': {('first_currency', 'second_currency')},
            },
        ),
    ]
