# Generated by Django 4.2.18 on 2025-06-01 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('symbol', models.CharField(max_length=8, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filled_at', models.DateTimeField(blank=True, null=True)),
                ('symbol', models.CharField(editable=False, max_length=17, unique=True)),
                ('state', models.CharField(choices=[('Active', 'active'), ('Suspend', 'suspend'), ('Deactive', 'deactive')], default='Active', max_length=15)),
                ('fee', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('base_currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='market_base_currency', to='currencies.currency')),
                ('quote_currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='market_quote_currency', to='currencies.currency')),
            ],
            options={
                'indexes': [models.Index(fields=['base_currency', 'quote_currency'], name='currencies__base_cu_a1d16f_idx')],
                'unique_together': {('base_currency', 'quote_currency')},
            },
        ),
    ]
