# Generated by Django 4.2.18 on 2025-06-01 07:05

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='fee',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1E-9'))]),
        ),
    ]
