# Generated by Django 4.2.18 on 2025-06-01 06:14

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filled_at', models.DateTimeField(blank=True, null=True)),
                ('order_type', models.CharField(blank=True, choices=[('Market', 'market'), ('Limit', 'limit')], default='Market', max_length=15, null=True)),
                ('order_side', models.CharField(choices=[('Buy', 'buy'), ('Sell', 'sell')], max_length=5)),
                ('order_state', models.CharField(choices=[('Waiting', 'waiting'), ('Filled', 'filled'), ('PartiallyFilled', 'partially_filled'), ('PartiallyFilledAndFinished', 'partially_filled_and_finished'), ('Canceled', 'canceled'), ('Error', 'error'), ('NotEnoughBalance', 'not_enough_balance'), ('AutomaticallyCanceled', 'automatically_canceled'), ('Idle', 'idle')], max_length=40)),
                ('price', models.DecimalField(decimal_places=16, max_digits=40, validators=[django.core.validators.MinValueValidator(1e-12)])),
                ('amount', models.DecimalField(decimal_places=8, max_digits=32, validators=[django.core.validators.MinValueValidator(1e-12)])),
                ('filled_amount', models.DecimalField(blank=True, decimal_places=8, default=Decimal('0.0'), max_digits=24, null=True)),
                ('low_limit', models.DecimalField(blank=True, decimal_places=16, max_digits=40, null=True, validators=[django.core.validators.MinValueValidator(1e-12)])),
                ('high_limit', models.DecimalField(blank=True, decimal_places=16, max_digits=40, null=True, validators=[django.core.validators.MinValueValidator(1e-12)])),
                ('target_market', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='target_to_market', to='currencies.market')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filled_at', models.DateTimeField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=16, max_digits=40, validators=[django.core.validators.MinValueValidator(1e-12)])),
                ('amount', models.DecimalField(decimal_places=8, max_digits=32, validators=[django.core.validators.MinValueValidator(1e-12)])),
                ('fee', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='maker_trades', to='orders.order')),
                ('taker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='taker_trades', to='orders.order')),
                ('trade_market', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='trade_to_market', to='currencies.market')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
