# Generated by Django 4.2.18 on 2025-05-31 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='target_market',
            field=models.CharField(choices=[], max_length=10),
        ),
    ]
